### ISSUE TITLE
No packages found

### ISSUE THREAD

**Issue by zxdawn** [Evidlo/remarkable_entware#5]
There's nothing when I try to search packages:

```
remarkable: ~/ opkg search '*shadow*'
remarkable: ~/ opkg search '*top*'
```

Here's the information of `opkg`:
```
remarkable: ~/ opkg -v
opkg version 0.1.8
remarkable: ~/ which opkg
/opt/bin/opkg
```

**Comment by Evidlo** [comment]
I also have that version of opkg.  

```
[root@remarkable ~] opkg search '*shadow*'
[root@remarkable ~] opkg search '*top*'
git - 2.19.2-2
htop - 2.2.0-2
python3-distutils - 3.7.1-2
python3-light - 3.7.1-2
python3-pydoc - 3.7.1-2
python3-setuptools - 39.0.1-1
[root@remarkable ~] opkg -v
opkg version 0.1.8
```

Is your `wget` broken?  You seemed to have linker errors in issue #4.

**Comment by zxdawn** [comment]
I'll test again from the beginning :+1: 
BTW, Why isn't `shadowsocks*` shown in your result?
From the [website](http://bin.entware.net/armv7sf-k2.6/), it's available
![image](https://user-images.githubusercontent.com/30388627/54529338-9a1f5480-49ba-11e9-8f07-f8c02a2491ed.png).

**Comment by zxdawn** [comment]
> I'll test again from the beginning 
> BTW, Why isn't `shadowsocks*` shown in your result?
> From the [website](http://bin.entware.net/armv7sf-k2.6/), it's available
> ![image](https://user-images.githubusercontent.com/30388627/54529338-9a1f5480-49ba-11e9-8f07-f8c02a2491ed.png).

Since I live in China, I want to use shadowsocks on rM to use VPN :cry:

**Comment by Evidlo** [comment]
```
[root@remarkable ~] opkg find '*shadow*'
shadow - 4.6-1 - Full versions of standard shadow utilities. Normally, you would not
 use this package, since the functionality in BusyBox is more than
 sufficient and much smaller.
shadow-chage - 4.6-1 - Full version of standard chage utility. Normally, you would not use this
 package, since the functionality in BusyBox is more than sufficient.
shadow-chfn - 4.6-1 - Full version of standard chfn utility. Normally, you would not use this
 package, since the functionality in BusyBox is more than sufficient.
shadow-chpasswd - 4.6-1 - Full version of standard chpasswd utility. Normally, you would not use this
...
```

**Comment by Evidlo** [comment]
So are these issues solved now?

**Comment by zxdawn** [comment]
I will check it this afternoon. I'm not at the office now.

Evan Widloski <notifications@github.com> 于 2019年3月19日周二 10:55写道：

**Comment by zxdawn** [comment]
@Evidlo 

Here're steps:
1. umount `/opt` and delete `/opt` folder and `/home/root/.entware`;
2. Since directly running `entware_install.sh` still get the error mentioned in https://github.com/Evidlo/remarkable_entware/issues/4#issue-420799875, I split the script into three parts:
- https://github.com/Evidlo/remarkable_entware/blob/ed30a3c8b5eaf20e7ceff35445d434637f75779b/entware_install.sh#L3-L48
- https://github.com/Evidlo/remarkable_entware/blob/ed30a3c8b5eaf20e7ceff35445d434637f75779b/entware_install.sh#L50-L88
- https://github.com/Evidlo/remarkable_entware/blob/ed30a3c8b5eaf20e7ceff35445d434637f75779b/entware_install.sh#L90-L102

There are no errors above.
3. Add /opt/bin & /opt/sbin to my PATH variable;
4. However, still no packages are found ...
```
remarkable: ~/ opkg search '*top*'
remarkable: ~/ opkg search '*shadow*'
```

**Comment by Evidlo** [comment]
You have to use `find`, not `search`.

**Comment by zxdawn** [comment]
Thanks:-D It works now~
